apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app-deployment
  labels:
    app: kanban-app
spec:
  replicas: 2  # 2 réplicas para alta disponibilidad
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
        - name: kanban-app
          image: kanban-app:latest  # Imagen pública
          imagePullPolicy: Never
          ports:
          - containerPort: 8080  # Puerto donde escucha el backend
          env:
          - name: DB_SERVER
            value: "kanban-postgres"  # Nombre del Service de PostgreSQL
          - name:  POSTGRES_DB
            value: "kanban"
          - name: POSTGRES_USER
            value: "kanban"
          - name: POSTGRES_PASSWORD
            value: "kanban"

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-app  # Nombre que usará el frontend para conectarse
spec:
  type: ClusterIP
  selector:
    app: kanban-app
  ports:
  - port: 8080
    targetPort: 8080
